#!/bin/bash

set -e
set -o pipefail

if test "$1" = ""; then
    echo "Version not provided" >&2
    exit 1
fi
if ! test -d "$2"; then
    echo "Source directory not provided" >&2
    exit 1
fi

# generate tarball version
echo "$1" > "$MESON_DIST_ROOT/.tarball-version"

# generate ChangeLog file
echo Generating ChangeLog...
(cd "$2" && exec git log --stat) > "$MESON_DIST_ROOT/ChangeLog"

# cleanup unwanted files
pushd "$MESON_DIST_ROOT"
rm \
    suppr.txt \
    git.mk \
    autogen.sh \
    build-aux/nss.supp \
    configure.ac \
    Makefile.am \
    src/Makefile.am \
    build-aux/glib-tap.mk \
    build-aux/tap-driver.sh \
    build-aux/tap-test
popd
